# file: .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && CGO_ENABLED=0 go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", "static"]
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[run]
  cmd = "./tmp/main"
  output = "air_app.log"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
  main_only = false
  level = debug

[misc]
  clean_on_exit = true