# file: .air.toml

root = "."
tmp_dir = "tmp"

[build]
  #cmd = "templ generate && CGO_ENABLED=0 go build -o ./tmp/main ."
  cmd = "templ generate && go build -o ./tmp/main main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["node_modules", "static", "temp_migrations"]
  exclude_file = []
  exclude_regex = ["_templ.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  include_file = []

